spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/trump_test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: "root"
    password: "076173"


mybatis:
  type-aliases-package: com.yuk.trump.entity
  mapper-locations: classpath:mapper/*.xml
