server:
  port: 8081

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.97.91:3306/trump_test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: "root"
    password: "076173"



mybatis:
  type-aliases-package: com.yuk.trump.entity
  mapper-locations: classpath:mapper/*.xml

#日志级别  TARCE < DEBUG < INFO < WARN < ERROR < FATAL
logging:
  path: /Users/ZhixiangWang/IdeaProjects/trump_Wangzhixiang/trump/
  file: trump.log
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"


redis:
  host: 47.102.97.91
  port: 6379
  timeout: 10
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500
